name: group_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Auth
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.6.7

  # Google & Maps
  google_sign_in: ^5.4.2
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.12
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0

  # UI
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0
  flutter_local_notifications: ^16.1.0
  flutter_typeahead: ^4.1.2

  # HTTP
  http: ^1.2.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dependency_overrides:
  google_maps_flutter_platform_interface: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
