// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASugX7Wzytfx7So3QJHefrJjBeSLXLIgI',
    appId: '1:377081049429:web:cb7156e6b7f66c99faffdc',
    messagingSenderId: '377081049429',
    projectId: 'sourcezero-b049d',
    authDomain: 'sourcezero-b049d.firebaseapp.com',
    storageBucket: 'sourcezero-b049d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyfRCpWwdGQqPWRV_u6BP9j2UIHXoggTs',
    appId: '1:377081049429:android:a1a4b29323863526faffdc',
    messagingSenderId: '377081049429',
    projectId: 'sourcezero-b049d',
    storageBucket: 'sourcezero-b049d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdtP8U48FshIX2CClNPFh1DdiHXb_tty4',
    appId: '1:377081049429:ios:f18406ef5f1eca06faffdc',
    messagingSenderId: '377081049429',
    projectId: 'sourcezero-b049d',
    storageBucket: 'sourcezero-b049d.firebasestorage.app',
    iosBundleId: 'com.example.groupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdtP8U48FshIX2CClNPFh1DdiHXb_tty4',
    appId: '1:377081049429:ios:f18406ef5f1eca06faffdc',
    messagingSenderId: '377081049429',
    projectId: 'sourcezero-b049d',
    storageBucket: 'sourcezero-b049d.firebasestorage.app',
    iosBundleId: 'com.example.groupProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASugX7Wzytfx7So3QJHefrJjBeSLXLIgI',
    appId: '1:377081049429:web:ddb9c2f1874eb191faffdc',
    messagingSenderId: '377081049429',
    projectId: 'sourcezero-b049d',
    authDomain: 'sourcezero-b049d.firebaseapp.com',
    storageBucket: 'sourcezero-b049d.firebasestorage.app',
  );
}
